### ISSUE TITLE
Page crashes with "Invalid time value"

### ISSUE THREAD

**Issue by ckniffen** [ripple/explorer#895]
The page crashes. https://devnet.xrpl.org/nft/00080000A5050355BC3A4B7E3F3D5A0F33AC44AC4C085A070B730272002F71D7

```
react-dom.production.min.js:216 RangeError: Invalid time value
    at Qt (utils.js:181:49)
    at MQ (TransactionTableRow.tsx:31:16)
    at d_ (react-dom.production.min.js:157:137)
    at NN (react-dom.production.min.js:267:460)
    at ON (react-dom.production.min.js:250:347)
    at xM (react-dom.production.min.js:250:278)
    at Qc (react-dom.production.min.js:250:138)
    at ib (react-dom.production.min.js:243:163)
    at react-dom.production.min.js:123:115
    at e.unstable_runWithPriority (scheduler.production.min.js:18:343)
K1 @ react-dom.production.min.js:216
a.componentDidCatch.n.callback @ react-dom.production.min.js:217
mE @ react-dom.production.min.js:131
yM @ react-dom.production.min.js:220
EM @ react-dom.production.min.js:259
e.unstable_runWithPriority @ scheduler.production.min.js:18
Lo @ react-dom.production.min.js:122
uo @ react-dom.production.min.js:252
ib @ react-dom.production.min.js:243
(anonymous) @ react-dom.production.min.js:123
e.unstable_runWithPriority @ scheduler.production.min.js:18
Lo @ react-dom.production.min.js:122
Q8 @ react-dom.production.min.js:123
Mi @ react-dom.production.min.js:122
_N @ react-dom.production.min.js:244
(anonymous) @ notifyManager.js:75
Promise.then (async)
P3 @ utils.js:322
t.flush @ notifyManager.js:74
t.batch @ notifyManager.js:30
t.dispatch @ query.js:392
t.setData @ query.js:85
onSuccess @ query.js:336
l @ retryer.js:58
Promise.then (async)
d @ retryer.js:116
_T @ retryer.js:156
t.fetch @ query.js:332
n.executeFetch @ queryObserver.js:199
n.onSubscribe @ queryObserver.js:40
t.subscribe @ subscribable.js:16
(anonymous) @ useBaseQuery.js:60
AM @ react-dom.production.min.js:262
e.unstable_runWithPriority @ scheduler.production.min.js:18
Lo @ react-dom.production.min.js:122
Za @ react-dom.production.min.js:261
(anonymous) @ react-dom.production.min.js:261
ne @ scheduler.production.min.js:16
b.port1.onmessage @ scheduler.production.min.js:12
```

**Comment by nick2432** [comment]
can i work on this?

**Comment by mvadari** [comment]
> can i work on this?

@nick2432 sure!
